### ISSUE TITLE
不支持 Material Design Xposed Installer 的重启到 Recovery

### ISSUE THREAD

**Issue by ivysrono** [liudongmiao/RebootWithoutSu#1]
Material Design Xposed Installer [21/07/2016]
http://forum.xda-developers.com/xposed/material-design-xposed-installer-t3137758

重启和软重启都没问题。

https://github.com/DVDAndroid/XposedInstaller/pull/109
看这里，今后这个原来的第三方管理器可能要变成官方版了。

**Comment by liudongmiao** [comment]
因为是针对原先的xposed installer的，新的话，需要重新实现。

**Comment by renyouguo** [comment]
现在新安装模块后通知栏激活并重启的提示，也只能激活不能重启。
dvd说有空会给你提交个PR。

**Comment by aviraxp** [comment]
https://github.com/aviraxp/RebootWithoutSu/commit/87974dd3138bb3a11673ad2e743bb7058cc11666

现在对于3.1需要重新调整，我这个只支持3.0.4.

**Comment by ivysrono** [comment]
@aviraxp 第三方版依然基于 3.0.4

**Comment by aviraxp** [comment]
看上面

**Comment by aviraxp** [comment]
有几处typo…………算了 不影响

**Comment by ivysrono** [comment]
谢谢，确实成功了。
这个已经可以提交PR了，一点一点来嘛~

**Comment by ivysrono** [comment]
@aviraxp 突然发现，这个issue已经不存在了。
至少 XposedInstaller_by_dvdandroid_26_11_16 + RebootWithoutSu 0.7 已经可以完全免 Root 了。
